from enum import Enum


class RobotSynthesis(str, Enum):
    OP = "OP"
    WORKING = "WORKING"
    HS = "HS"
    ANTI_THEFT = "ANTI_THEFT"
    UI_CHECK_STATE = "UI_CHECK_STATE"
    UI_STARTING_STATE = "UI_STARTING_STATE"
    UI_CONTINUE_STATE = "UI_CONTINUE_STATE"
    UI_WAIT_WORKING_STATE = "UI_WAIT_WORKING_STATE"
    UI_CREATE_FIELD_STATE = "UI_CREATE_FIELD_STATE"
    UI_CALIBRATE_STATE = "UI_CALIBRATE_STATE"
    UI_ACTUATOR_SCREENING_STATE = "UI_ACTUATOR_SCREENING_STATE"
    UI_AUTO_RESTART_APP = "UI_AUTO_RESTART_APP"
    UI_RESTART_APP = "UI_RESTART_APP"
